# Generated by Django 4.1.1 on 2022-12-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(default=0)),
                ('catagory', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
