# Generated by Django 4.1.1 on 2022-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
